apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliance-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zoeleve/product-compliance-dashboard.git
    targetRevision: HEAD
    path: k8s/helm/compliance-dashboard
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: compliance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
